# Markdownlint configuration for swift-complexity

# Disable rules that conflict with GitHub markdown
MD013: false  # Line length
MD033: false  # Inline HTML
MD041: false  # First line in file should be a top level header

# Configure specific rules
MD007:
  indent: 2  # Unordered list indentation

MD024:
  allow_different_nesting: true  # Allow duplicate headers at different levels

MD029:
  style: "ordered"  # Ordered list item prefix

MD040:
  allowed_languages: 
    - bash
    - swift
    - json
    - yaml
    - console
  language_only: false

# Ignore specific patterns
extends: null